In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('properties_data.csv')
print(dataset.head())

        id          neighborhood   latitude  longitude    price  size_in_sqft  \
0  5528049         Palm Jumeirah  25.113208  55.138932  2700000          1079   
1  6008529         Palm Jumeirah  25.106809  55.151201  2850000          1582   
2  6034542  Jumeirah Lake Towers  25.063302  55.137728  1150000          1951   
3  6326063       Culture Village  25.227295  55.341761  2850000          2020   
4  6356778         Palm Jumeirah  25.114275  55.139764  1729200           507   

   price_per_sqft  no_of_bedrooms  no_of_bathrooms quality  ...  private_pool  \
0         2502.32               1                2  Medium  ...         False   
1         1801.52               2                2  Medium  ...         False   
2          589.44               3                5  Medium  ...         False   
3         1410.89               2                3     Low  ...         False   
4         3410.65               0                1  Medium  ...         False   

   security  shared_gym  s

In [6]:
dataset2 = dataset.drop(['neighborhood', 'longitude', 'latitude','price_per_sqft','id','quality'], axis=1)
dataset2.head()

price  size_in_sqft  no_of_bedrooms  no_of_bathrooms  maid_room  \
0  2700000          1079               1                2      False   
1  2850000          1582               2                2      False   
2  1150000          1951               3                5       True   
3  2850000          2020               2                3      False   
4  1729200           507               0                1      False   

   unfurnished  balcony  barbecue_area  built_in_wardrobes  central_ac  ...  \
0        False     True           True               False        True  ...   
1        False     True          False                True        True  ...   
2         True     True          False                True       False  ...   
3         True     True          False               False       False  ...   
4        False    False          False                True        True  ...   

   private_pool  security  shared_gym  shared_pool  shared_spa  study  \
0         False     False        True        False       False  False   
1         False     False        True         True       False  False   
2         False      True        True         True       False  False   
3         False     False       False        False       False  False   
4         False      True        True         True        True  False   

   vastu_compliant  view_of_landmark  view_of_water  walk_in_closet  
0            False             False           True           False  
1            False             False           True           False  
2            False              True           True            True  
3            False             False          False           False  
4            False              True           True           False  

[5 rows x 32 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
dataset_encoded = dataset2.iloc[:,5:33]

for i in dataset_encoded:
    dataset2[i] = le.fit_transform(dataset_encoded[i])

dataset2.head()

price  size_in_sqft  no_of_bedrooms  no_of_bathrooms  maid_room  \
0  2700000          1079               1                2      False   
1  2850000          1582               2                2      False   
2  1150000          1951               3                5       True   
3  2850000          2020               2                3      False   
4  1729200           507               0                1      False   

   unfurnished  balcony  barbecue_area  built_in_wardrobes  central_ac  ...  \
0            0        1              1                   0           1  ...   
1            0        1              0                   1           1  ...   
2            1        1              0                   1           0  ...   
3            1        1              0                   0           0  ...   
4            0        0              0                   1           1  ...   

   private_pool  security  shared_gym  shared_pool  shared_spa  study  \
0             0         0           1            0           0      0   
1             0         0           1            1           0      0   
2             0         1           1            1           0      0   
3             0         0           0            0           0      0   
4             0         1           1            1           1      0   

   vastu_compliant  view_of_landmark  view_of_water  walk_in_closet  
0                0                 0              1               0  
1                0                 0              1               0  
2                0                 1              1               1  
3                0                 0              0               0  
4                0                 1              1               0  

[5 rows x 32 columns]

In [8]:
columns = [ 'size_in_sqft', 'no_of_bedrooms', 'no_of_bathrooms' ,'maid_room' ,'unfurnished' ,            
               'balcony' , 'barbecue_area' , 'built_in_wardrobes', 'central_ac' ,'childrens_play_area' ,'childrens_pool' ,         
                'concierge' , 'covered_parking','kitchen_appliances' ,'lobby_in_building','maid_service' ,'networked',
                'pets_allowed' ,'private_garden' ,'private_gym' ,'private_jacuzzi' ,'private_pool' ,'security' ,'shared_gym' ,  
                'shared_pool' ,'shared_spa' ,'study' ,'vastu_compliant' ,'view_of_landmark' ,'view_of_water' ,'walk_in_closet' ,
                'price'] 
dataset2 = dataset2[columns]

In [9]:
dataset2.head()

size_in_sqft  no_of_bedrooms  no_of_bathrooms  maid_room  unfurnished  \
0          1079               1                2      False            0   
1          1582               2                2      False            0   
2          1951               3                5       True            1   
3          2020               2                3      False            1   
4           507               0                1      False            0   

   balcony  barbecue_area  built_in_wardrobes  central_ac  \
0        1              1                   0           1   
1        1              0                   1           1   
2        1              0                   1           0   
3        1              0                   0           0   
4        0              0                   1           1   

   childrens_play_area  ...  security  shared_gym  shared_pool  shared_spa  \
0                    1  ...         0           1            0           0   
1                    1  ...         0           1            1           0   
2                    0  ...         1           1            1           0   
3                    0  ...         0           0            0           0   
4                    0  ...         1           1            1           1   

   study  vastu_compliant  view_of_landmark  view_of_water  walk_in_closet  \
0      0                0                 0              1               0   
1      0                0                 0              1               0   
2      0                0                 1              1               1   
3      0                0                 0              0               0   
4      0                0                 1              1               0   

     price  
0  2700000  
1  2850000  
2  1150000  
3  2850000  
4  1729200  

[5 rows x 32 columns]

In [10]:
X = dataset2.iloc[:,0:32].values
Y = dataset2.iloc[:,-1].values

In [11]:
print(X)

[[1079 1 2 ... 1 0 2700000]
 [1582 2 2 ... 1 0 2850000]
 [1951 3 5 ... 1 1 1150000]
 ...
 [1930 3 5 ... 0 0 2900000]
 [740 1 2 ... 1 1 675000]
 [800 1 2 ... 1 0 760887]]


In [12]:
print(Y)

[2700000 2850000 1150000 ... 2900000  675000  760887]


In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state=100)

# Multiple Linear Regression

In [15]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [17]:
import numpy as np
y_pred = regressor.predict(X_test)
# Set the precision to 2 digits
np.set_printoptions(precision=2)

# Round the predicted prices to 2 digits
y_pred = np.round(y_pred, 2)


In [19]:
print(X_test[0])
print(Y_test[0])

[1186 1 2 False 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1750000]
1750000


In [27]:
y_pred = regressor.predict([X_test[0]])
np.set_printoptions(precision=2)
print(y_pred)

[1749999.9999999986]


In [32]:
from sklearn.metrics import mean_squared_error

# Make predictions
y_pred = regressor.predict(X_test)

# Calculate the MSE
mse = mean_squared_error(Y_test, y_pred)

# Print the MSE
print(mse)


5.8015220727169105e-18


# Decision Tree Regression

In [33]:
from sklearn.tree import DecisionTreeRegressor
regressor1 = DecisionTreeRegressor(max_depth = 5)
regressor1.fit(X_test, Y_test)

DecisionTreeRegressor(max_depth=5)

In [34]:
print(X_test[0])
print(Y_test[0])

[1186 1 2 False 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1750000]
1750000


In [35]:
y_pred = regressor1.predict([X_test[0]])
np.set_printoptions(precision=2)
y_pred = np.round(y_pred, 2)
print(y_pred)

[1725148.89]


In [37]:
from sklearn.metrics import mean_squared_error

# Make predictions
y_pred = regressor1.predict(X_test)

# Calculate the MSE
mse = mean_squared_error(Y_test, y_pred)

# Print the MSE
print(mse)


9846202889.143847


#SV Regression

In [38]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_test, Y_test)

SVR()

In [39]:
y_pred = regressor1.predict([X_test[0]])
np.set_printoptions(precision=2)
y_pred = np.round(y_pred, 2)
print(y_pred)

[1725148.89]


In [40]:
from sklearn.metrics import mean_squared_error

# Make predictions
y_pred = regressor1.predict(X_test)

# Calculate the MSE
mse = mean_squared_error(Y_test, y_pred)

# Print the MSE
print(mse)

9846202889.143847
